{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a4825c96_e3e5556f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1006192
      },
      "writtenOn": "2021-10-06T00:17:23Z",
      "side": 1,
      "message": "The CI failure is unrelated.",
      "revId": "7bc39962e094ecd078b4b72af5eafd1e4395a4b6",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}